[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "frontend/netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  VITE_RECAPTCHA_SITE_KEY = "6LcuYWEtAAAAADkDa8k86iTjoLSe9asJeO1Ksni2"
  GMAIL_USER = "kunallohaniya@gmail.com"
  GMAIL_APP_PASS = "brra oobd pzxx lqks"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 5174
