[build]
  command = "npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_RECAPTCHA_SITE_KEY = "6LdVtkwsAAAAAKhPAfLpYaz4Hu2hWxsG8Qd_5wAA"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
