[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "frontend/netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  VITE_RECAPTCHA_SITE_KEY = "6LcuYWEtAAAAADkDa8k86iTjoLSe9asJeO1Ksni2"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 5174

